wip(misc): check target dir prior sync

diff --git a/modules/media/templates/media_sync.erb b/modules/media/templates/media_sync.erb
--- a/modules/media/templates/media_sync.erb
+++ b/modules/media/templates/media_sync.erb
@@ -1,6 +1,10 @@
 #!/bin/sh
 
-cd <%=@media_root%>/media
+if ! test -d "<%=@media_root%>/media; then
+    echo "Missing media root" >&2
+    exit 1
+fi
+cd "<%=@media_root%>/media"
 for mediadir in Docu EPTV Movies Series Training
 do
     test -d "$mediadir" || continue
diff --git a/modules/packages/templates/sync_repository.erb b/modules/packages/templates/sync_repository.erb
--- a/modules/packages/templates/sync_repository.erb
+++ b/modules/packages/templates/sync_repository.erb
@@ -7,7 +7,11 @@ REMOTE_USER=<%=@sync_user%>
 <% end -%>hostname=`hostname -f || hostname`
 ret=1
 
-cd <%=@web_root%>
+if ! test -d "<%=@web_root%>"; then
+    echo "Missing repository root" >&2
+    exit 1
+fi
+cd "<%=@web_root%>"
 
 if rsync -avWxP --exclude='*lost+found*' --exclude='*modeles/virtualbox-peerio*' --rsh="ssh -p$REMOTE_PORT" --delete $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/ .; then
     ret=0
diff --git a/modules/subsonic/templates/sync.erb b/modules/subsonic/templates/sync.erb
--- a/modules/subsonic/templates/sync.erb
+++ b/modules/subsonic/templates/sync.erb
@@ -13,7 +13,11 @@ elif ls /tmp/subsonic_sync.* 2>/dev/null | grep [0-9] >/dev/null; then
     exit 1
 fi
 
-cd $ROOT
+if ! test -d "$ROOT"; then
+    echo "Missing subsonic root" >&2
+    exit 1
+fi
+cd "$ROOT"
 for remoteitem in $REMOTES
 do
     if echo $remoteitem | grep : >/dev/null; then
